### ISSUE TITLE
Product available for sale or not

### ISSUE THREAD

**Issue by DrAqeel416** [manhoosbilli1/DIY-Arduino-Incubator#2]
Aslam alukum. Very interesting development going on. Been following you for  a year now. I want to use your product. Kindly share your WhatsApp number.

**Comment by manhoosbilli1** [comment]
Walaikum Salam,

Really appreciate it. yes, the development is still undergoing and with time being so scarce nowadays and with me being busy in a company i haven't had the time to complete the project for YouTube yet.

But let me know how i can help and i'll do my best.
My number: 03331304910 (whatsapp enabled)

Regards

________________________________

Shoaib Mustafa


________________________________
From: DrAqeel416 ***@***.***>
Sent: Monday, July 17, 2023 1:31 AM
To: manhoosbilli1/DIY-Arduino-Incubator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [manhoosbilli1/DIY-Arduino-Incubator] Product available for sale or not (Issue #2)


Aslam alukum. Very interesting development going on. Been following you for a year now. I want to use your product. Kindly share your WhatsApp number.
